spring.application.name=spring-ai

spring.ai.openai.api-key=${TOGETHER_AI_API_KEY}
spring.ai.openai.base-url=https://api.together.ai
spring.ai.openai.chat.options.model=ServiceNow-AI/Apriel-1.6-15b-Thinker
#spring.ai.openai.image.options.model=Lykon/DreamShaper